function [ ] = createButton()

    global initFig;
    global origem_ui;
    global distino_ui;
    uicontrol('style', 'pushbutton',...
            'parent', initFig,...
            'string', '重新绘制',...
            'fontsize', 14,...
            'Position', [0, 400, 100, 80],...
            'callback', 'clf; createButton(); createTopoPlot(topo);');
    origem_ui = uicontrol('style', 'edit',...
            'parent', initFig,...
            'string', '输入起点',...
            'fontsize', 14,...
            'Position', [0, 300, 100, 80],...
            'callback', 'from_ = mystr2num(origem_ui.String);');
    distino_ui = uicontrol('style', 'edit',...
            'parent', initFig,...
            'string', '输入终点',...
            'fontsize', 14,...
            'Position', [0, 200, 100, 80],...
            'Max', 1',...
            'callback', 'to_ = mystr2num(distino_ui.String);');
    uicontrol('style', 'pushbutton',...
            'parent', initFig,...
            'string', '普通算法',...
            'fontsize', 14,...
            'Position', [0, 100, 100, 80],...
            'callback', 'dijkstra(length(topo), topo, from_, to_);');
    uicontrol('style', 'pushbutton',...
            'parent', initFig,...
            'string', '优化算法',...
            'fontsize', 14,...
            'Position', [0, 0, 100, 80],...
            'callback', 'dijkstraPrior(length(topo), topo, from_, to_);');
end

